import Head from 'next/head'
import Header from '../components/Header'
import Main from "../components/Main"
import TransactionHistory from '../components/TransactionHistory'

const styles = {
  wrapper: `bg-[#2D242F] text-white select-none flex flex-col justify-between h-fit h-full bg-cover h-max`,
}

export default function Home() {
  return (
    <div className={styles.wrapper}>
      <Head>
        <title>Uniswap Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main />
     <TransactionHistory />
    </div>
  )
}
